mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from mysite.bands.views import BandForm
from mysite.bands.views import MemberForm
admin.autodiscover()

urlpatterns = patterns('mysite.bands.views',

    url(r'^$', 'home', name='home'),
    url(r'^bands/$', 'band_listing', name='bands'),
    url(r'^bands/(?P<pk>\d+)/$', 'band_detail', name='band_detail'),
    url(r'^bandform/', BandForm.as_view(), name='band_form'),
    url(r'^memberform/', MemberForm.as_view(), name='member_form'),
    url(r'^contact/$', 'band_contact', name='contact'),
    url(r'^protected/$', 'protected_view', name='protected'),
    url(r'^accounts/login/$', 'message'),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^logout/$', 'logout',name='logout'),
)

mysite/bands/models.py
from django.db import models
from django.db.models.signals import post_save

class Band(models.Model):

    """A model of a rock band."""
    name = models.CharField(max_length=200)
    can_rock = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'band'
        verbose_name_plural = 'bands'

    def __str__(self):
        return self.name

    # count members by band
    # conta os membros por banda
    def get_members_count(self):
        return self.band.count()

    # retorna a url no formato /bands/1
    def get_band_detail_url(self):
        return u"/bands/%i" % self.id


class Member(models.Model):

    """A model of a rock band member."""
    name = models.CharField("Member's name", max_length=200)
    instrument = models.CharField(choices=(
        ('g', "Guitar"),
        ('b', "Bass"),
        ('d', "Drums"),
        ('v', "Vocal"),
        ('p', "Piano"),
    ),
        max_length=1
    )

    band = models.ForeignKey("Band", related_name='band')

    class Meta:
        ordering = ['name']
        verbose_name = 'member'
        verbose_name_plural = 'members'

    def __str__(self):
        return self.name


def my_callback(sender, **kwargs):
        print ("")
        print ("Model salva!")
        print ("")

post_save.connect(my_callback)
    

mysite/bands/forms.py
from django import forms
from .models import Band, Member


class BandContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class BandForm(forms.ModelForm):

    class Meta:
        model = Band


class MemberForm(forms.ModelForm):

    class Meta:
        model = Member

mysite/bands/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Band, Member
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse
from mysite.bands.forms import BandContactForm
from django.contrib.auth import logout as auth_logout
from django.template.context import RequestContext

#def home(request):
 #   return HttpResponse('Welcome to the site!')

def home(request):
    return render(request, 'home.html',{'user':request.user})

def band_listing(request):
    """ A view of all bands. """
    bands = Band.objects.all()
    var_get_search = request.GET.get('search_box')
    if var_get_search is not None:
        bands = bands.filter(name__icontains=var_get_search)
    return render(request, 'bands/band_listing.html', {'bands': bands})

def band_contact(request):
    """ A example of form """
    if request.method == 'POST':
        form = BandContactForm(request.POST)
    else:
        form = BandContactForm()
    return render(request, 'bands/band_contact.html', {'form': form})

def band_detail(request, pk):
    """ A view of all members by bands. """
    band = Band.objects.get(pk=pk)
    members = Member.objects.all().filter(band=band)
    context = {'members': members, 'band': band,'user':request.user}
    return render(request, 'bands/band_detail.html', context)

class BandForm(CreateView):
    template_name = 'bands/band_form.html'
    model = Band
    success_url = 'bands/'

class MemberForm(CreateView):
    template_name = 'bands/member_form.html'
    model = Member
    success_url = 'bands/'

@login_required(login_url='/accounts/login/')
def protected_view(request):
    """ A view that can only be accessed by logged-in users """
    return render(request, 'bands/protected.html', {'current_user': request.user})

def message(request):
    """ Message if is not authenticated. Simple view! """
    return HttpResponse('Access denied!')

def logout(request):
    auth_logout(request)
    return redirect('/')

mysite/bands/templates/bands/band_contact.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
    <title>Band Contact</title>
{% endblock title %}

{% block content %}

    <h1>Send e-mail</h1>
    <form class="form" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% bootstrap_icon "star" %} Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

mysite/bands/templates/bands/band_detail.html
{% extends "base.html" %}

{% block title %}
    <title>Member Listing</title>
{% endblock title %}

{% block content %}
    <h2>Members of {{ band.name }}</h2>
    <ul class="list-group">
        {% for member in members %}
            {% if member.instrument == 'v' %}
                <li class="list-group-item list-group-item-info">
            {% else %}
                <li class="list-group-item">
            {% endif %}
                    {{ member.name }} - {{ member.get_instrument_display }}
                </li>
        {% endfor %}
    </ul>
    <div class="fb-like" data-href="http://127.0.0.1:8000/bands/{{band.pk}}/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    <br>
    <div class="fb-comments" data-href="http://127.0.0.1:8000/bands/{{band.pk}}/" data-numposts="5"></div>
{% endblock content %}

mysite/bands/templates/bands/band_details.html
{% extends "base.html" %}

{% block title %}
    <title>Member Listing</title>
{% endblock title %}

{% block content %}
    <h2>Members of {{ band.name }}</h2>
    <ul class="list-group">
        {% for member in members %}
            {% if member.instrument == 'v' %}
                <li class="list-group-item list-group-item-info">
            {% else %}
                <li class="list-group-item">
            {% endif %}
                    {{ member.name }} - {{ member.get_instrument_display }}
                </li>
        {% endfor %}
    </ul>
{% endblock content %}

mysite/bands/templates/bands/band_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
    <title>Band Form</title>
{% endblock title %}

{% block content %}

    <h1>Create band</h1>
    <form class="form col-sm-4" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

mysite/bands/templates/bands/band_listing.html
{% extends "base.html" %}

{% block title %}
    <title>Band Listing</title>
{% endblock title %}

{% block content %}
    <!-- search form -->
    <form class="navbar-form navbar-right" action="." method="get">
        <input id="search_box" name="search_box" type="text" placeholder="Search..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>

    <h1>All Bands</h1>
    {% for band in bands %}
        <ul class="list-group">
          <li class="list-group-item">
            <span class="badge">{{ band.get_members_count }}</span>
            <h4><a href="{{ band.get_band_detail_url }}">{{ band.name }}</a></h4>
            {% if band.can_rock %}
                <p>This band can rock!</p>
            {% endif %}
          </li>
        </ul>
    {% endfor %}
{% endblock content %}

mysite/bands/templates/bands/member_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
    <title>Member Form</title>
{% endblock title %}

{% block content %}

    <h1>Create member</h1>
    <form class="form col-sm-4" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

mysite/bands/templates/bands/protected.html
{% extends "base.html" %}

{% block title %}
    <title>Protected</title>
{% endblock title %}

{% block content %}
    <h1>Protected page</h1>

    <p>Logged as: {{ user }}</p>
{% endblock content %}

mysite/bands/templates/base.html
<html>
<head>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

  <link rel="icon" href="http://s3.amazonaws.com/snaaakes-static/img/colophon/django.png">


    {% block title %}
        <title>Django 1.7</title>
    {% endblock title %}

  <style>
    body {
      padding-top: 70px;
    }
  </style>

</head>

<body>

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.6&appId=920920224719990";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  {% include "menu.html" %}

  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

  {% block javascript %}
    <!-- Latest JQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  {% endblock javascript %}

</body>
</html>

mysite/bands/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>Bandas FGA</h1>
    <p>Este site permite adicionar bandas e membros destas bandas</p>
</div>
{% endblock content %}

mysite/bands/templates/menu.html
<!-- Menu -->
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'bands' %}">Bands</a></li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'protected' %}">Protected</a></li>
        <!-- to resolve NoReverseMatch for 'admin' -->
        <li><a href="{% url 'admin:index' %}">Administration</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Create<b class="caret"></b></a>
          <ul class="dropdown-menu">
           <li><a href="{% url 'band_form' %}">Create band</a></li>
           <li><a href="{% url 'member_form' %}">Create member</a></li>
          </ul>
        </li>
        <li class="dropdown">
          {% if user and not user.is_anonymous %}
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello, {{ user.get_full_name }}!<b class="caret"></b></a>
            <ul class="dropdown-menu">
             <li><a href="/logout">Logout</a></li>
            </ul>
          {% else %}
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
            <ul class="dropdown-menu">
             <li><a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a></li>
             <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a></li>
             <li><a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Login with Twitter</a></li>
            </ul>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</div>